service: fastapi-serverless

frameworkVersion: '4'

stages:
  prod:
    params:
      log_level: "INFO"
  stage:
    params:
      log_level: "INFO"
  dev:
    params:
      log_level: "DEBUG"

provider:
  name: aws
  runtime: python3.11
  environment:
    DEBUG: ${env:DEBUG, "false"}
    LOG_LEVEL: ${param:log_level}

functions:
  api:
    package:
      patterns:
        - 'app/**'
    handler: app.main.handler
    events:
      - http:
          method: any
          path: /{proxy+}

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    zip: true
    fileName: requirements-prod.txt

plugins:
  - serverless-python-requirements
  - serverless-offline
